research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

linkedin_post_task:
  description: >
    Create an engaging LinkedIn post about {topic}.
    Focus on one key insight or development that would be valuable for professionals
    in the industry about {topic} . Include relevant hashtags and ensure the content is
    optimized for LinkedIn's platform (keep it under 3000 characters).
    Consider including:
    - A hook to grab attention
    - The main insight or development
    - Practical implications or applications
    - A call to action or thought-provoking question
    - 3-5 relevant hashtags
  expected_output: >
    A complete LinkedIn post ready for publishing, including main content and hashtags.
    The post should be engaging, informative, and professionally written.
  agent: content_creator
  output_file: report.md